import type { Article } from "@/lib/types";

/**
 * The help centre, 8 articles.
 *
 * Two deliberate properties:
 *  1. Operational detail (exact error strings, exact windows, exact settings paths),
 *     because a support agent that answers in generalities is useless and, worse,
 *     ungradeable — there is nothing to check the reply against.
 *  2. Deliberate gaps. There is nothing here about DPAs, sub-processors, discounts,
 *     or the roadmap. The escalation half of the exam depends on questions this KB
 *     genuinely cannot answer, so the agent's only honest move is to hand off.
 */
export const SEED_ARTICLES: Article[] = [
  {
    id: "kb-zendesk-connect",
    title: "Connecting Zendesk to OpenCX",
    tags: ["zendesk", "integration", "connect", "sync", "api token", "admin"],
    updatedAt: "2025-11-04",
    body: `Connect Zendesk from Settings > Integrations > Zendesk > Connect.

You need three things: your Zendesk subdomain, the email address of a Zendesk user with the **Admin** role, and an API token generated by that admin user.

The most common failure looks like success. If the API token was generated by a user with the Agent role rather than Admin, the connection test passes and the integration shows "Connected", but no tickets are imported. Zendesk returns 403 Forbidden on the ticket export endpoint, which we log but do not surface on the integration card.

To confirm this is what happened, open Settings > Integrations > Zendesk > Sync log and look for repeated "403 Forbidden /api/v2/incremental/tickets" entries. The fix is to generate a new API token as an Admin user and reconnect; there is no way to grant the export scope to an Agent-role token.

After a successful connect, the first backfill covers the last 30 days and completes within 10 minutes for most workspaces. Ongoing sync polls every 2 minutes.`,
  },
  {
    id: "kb-intercom-sync-stops",
    title: "Intercom sync stops working after it was fine",
    tags: ["intercom", "integration", "sync", "401", "oauth", "token", "revoked"],
    updatedAt: "2025-10-22",
    body: `Intercom connects over OAuth, and the access token belongs to the Intercom user who authorised the app — not to the workspace.

That means the token is revoked when that person is deactivated, has their Intercom seat removed, or loses admin permissions. Sync stops immediately. Existing conversations stay in OpenCX; nothing new arrives.

The signature is a 401 in Settings > Integrations > Intercom > Integration log:
"401 Unauthorized — Access Token Invalid".

We do not auto-reconnect, because silently re-authorising as a different user would change which conversations OpenCX can see.

Fix: reconnect the integration. To stop it recurring, authorise with a dedicated Intercom service account that no one offboards, and give it the Full Access role. Reconnecting does not duplicate conversations; we de-duplicate on the Intercom conversation ID.`,
  },
  {
    id: "kb-api-rate-limits",
    title: "API rate limits and 429 responses",
    tags: ["api", "rate limit", "429", "throttle", "bulk", "import", "retry-after"],
    updatedAt: "2025-12-01",
    body: `The OpenCX REST API allows 120 requests per minute per workspace, with a short burst allowance of 200. Limits are per workspace, not per API key, so adding keys does not add capacity.

Exceeding the limit returns HTTP 429 with a Retry-After header in seconds. Every response also carries X-RateLimit-Remaining and X-RateLimit-Reset.

If you are importing historical tickets one request at a time you will hit this within seconds. Use the bulk endpoint instead: POST /v1/bulk/tickets accepts up to 500 tickets per call and counts as a single request against the limit. A 100,000 ticket import is 200 bulk calls, which fits comfortably inside the limit.

Clients should honour Retry-After and back off exponentially. Retrying immediately on 429 extends the throttle window rather than clearing it.

Sustained higher limits are available on Enterprise plans and are configured per workspace by the account team.`,
  },
  {
    id: "kb-refund-policy",
    title: "Refund policy for self-serve plans",
    tags: ["refund", "billing", "policy", "14 days", "self-serve", "renewal"],
    updatedAt: "2025-09-15",
    body: `Self-serve monthly and annual plans purchased directly with a card can be refunded in full within **14 days of the initial purchase**. Request it from Settings > Billing > Request refund; refunds return to the original payment method within 5 to 10 business days.

Two things this policy does not cover:

1. **Renewal charges.** Automatic renewals are outside the 14-day window by definition and are not refundable under this policy. You can cancel from Settings > Billing at any time to stop the next renewal; cancellation takes effect at the end of the paid period.
2. **Enterprise and invoiced contracts.** These are governed by the order form, not by this policy.

Exceptions to either of the above are not decided in the help centre. They are handled case by case by the billing team, who are the only people who can approve one.`,
  },
  {
    id: "kb-seat-management",
    title: "Inviting teammates and managing seats",
    tags: ["seat", "invite", "teammate", "user", "licence", "admin", "billing"],
    updatedAt: "2025-11-19",
    body: `Workspace Owners and Admins can invite teammates from Settings > Team > Invite. Agents cannot invite.

If the invite button returns "Seat limit reached for your plan", every seat you are paying for is occupied. Two options:

- Free a seat: Settings > Team, open the member, Remove from workspace. The seat is available immediately and their conversations stay assigned to them for reporting.
- Add seats: Settings > Billing > Seats. Additional seats are prorated for the remainder of the current billing period and charged immediately.

Pending invites hold a seat for 7 days, then expire and release it. An invite that has expired must be resent; the original link stops working.

Deactivated members do not hold a seat. Members with the Owner role cannot be removed until ownership is transferred.`,
  },
  {
    id: "kb-agent-handoff",
    title: "AI agent handoff thresholds",
    tags: ["ai agent", "handoff", "escalation", "confidence", "threshold", "bot", "human"],
    updatedAt: "2025-12-10",
    body: `The AI agent hands a conversation to a human when any of these is true:

- Its confidence in the answer is below the handoff threshold. The default is 0.6.
- The customer asks for a human twice in the same conversation.
- Two consecutive customer messages are scored as negative sentiment.
- The message matches one of your handoff keywords (Settings > AI Agent > Handoff > Keywords). Legal, cancel and chargeback are on the default list.

Change the threshold in Settings > AI Agent > Handoff. Raising it toward 1.0 hands off more often and answers less; lowering it toward 0 answers more and risks confident wrong answers. Most workspaces settle between 0.55 and 0.7.

Threshold changes apply to new conversations only, and take about a minute to propagate. The Handoff report shows, per day, how many conversations were handed off and which trigger fired, which is the fastest way to tell whether a change did what you wanted.`,
  },
  {
    id: "kb-okta-sso",
    title: "Okta SSO (SAML 2.0) setup and user lifecycle",
    tags: ["okta", "sso", "saml", "provisioning", "scim", "identity", "login"],
    updatedAt: "2025-10-08",
    body: `OpenCX supports SAML 2.0 single sign-on with Okta on Enterprise plans. Add the OpenCX app in Okta, paste the metadata URL into Settings > Security > SSO, and enable Require SSO once you have tested a login.

Just-in-time provisioning is on by default: a user who authenticates through Okta for the first time gets an OpenCX account with the Agent role and consumes a seat.

**SCIM is not supported yet.** Because provisioning is JIT-only, the lifecycle is one-directional. Suspending or deleting a user in Okta stops them signing in, but it does **not** remove their OpenCX account and it does **not** release their seat, so you keep being billed for them.

Until SCIM ships, offboarding is a two-step process: remove the user in Okta, then remove them in OpenCX from Settings > Team. Workspaces that offboard in bulk usually script the second step against DELETE /v1/members/{id}.`,
  },
  {
    id: "kb-webhook-retries",
    title: "Webhook delivery, retries and replay",
    tags: ["webhook", "retry", "delivery", "timeout", "endpoint", "disabled", "replay"],
    updatedAt: "2025-11-27",
    body: `Your endpoint must return a 2xx status within 5 seconds. Anything else — a non-2xx, a timeout, a TLS error — counts as a failed delivery. Do the work asynchronously and acknowledge first; slow handlers are the most common cause of "missing" events.

Failed deliveries are retried 5 times with exponential backoff: after 1 minute, 5 minutes, 25 minutes, 2 hours and 6 hours. Total retry span is a little over 8 hours.

After the 5th failure the endpoint is **automatically disabled** and an email is sent to all workspace Owners. Nothing is queued while an endpoint is disabled — events that occur during that period are not delivered when you re-enable it.

Delivery history is kept for 7 days at Settings > Webhooks > Deliveries. You can filter to failed deliveries and replay them individually or in bulk from there. Anything older than 7 days is gone and must be backfilled through the REST API.`,
  },
];
